### ISSUE TITLE
Auto Merge Pull Request

### ISSUE THREAD

**Issue by Team-thedatatribune** [Team-thedatatribune/IPL-Analysis#42]
Please have a look onto the file [contributors.yml](https://github.com/Team-thedatatribune/IPL-Analysis/blob/master/.github/workflows/contributors.yml) and try to resolve the issue, due to which it **fails** to execute.  
  
@Siddhant-K-code

**Comment by Siddhant-K-code** [comment]
I think, bot doesn't have power to merge PR automatically

**Comment by ravi-prakash1907** [comment]
Perhaps! Btw, thanks for your efforts.. :))
